[package]
name = "cryogen"
version = "0.1.0"
authors = ["Ferris Tseng <ferristseng@fastmail.fm>"]

[dependencies]
tera = "0.8.*"
clap = "2.20.*"
cryogen_prelude = { version = "*", path = "../prelude" }
cryogen_plugin_json = { version = "*", path = "../plugin-json", optional = true }
cryogen_plugin_markdown = { version = "*", path = "../plugin-markdown", optional = true }
cryogen_plugin_yaml = { version = "*", path = "../plugin-yaml", optional = true }

[features]
default = [
    "json",
    "markdown",
    "yaml"
]

json = ["cryogen_plugin_json"]
markdown = ["cryogen_plugin_markdown"]
yaml = ["cryogen_plugin_yaml"]
