[package]
name = "cryogen"
version = "0.1.0"
authors = ["Ferris Tseng <ferristseng@fastmail.fm>"]

[dependencies]
tera = "0.8.*"
clap = "2.20.*"
lib = { version = "*", path = "../lib" }
feature_json = { version = "*", path = "../feature-json", optional = true }
feature_markdown = { version = "*", path = "../feature-markdown", optional = true }
feature_yaml = { version = "*", path = "../feature-yaml", optional = true }

[features]
default = [
    "json",
    "markdown",
    "yaml"
]

json = ["feature_json"]
markdown = ["feature_markdown"]
yaml = ["feature_yaml"]
