[package]
name = "cryogen_plugin_json"
version = "0.1.0"
authors = ["Ferris Tseng <ferristseng@fastmail.fm>"]

[dependencies]
clap = "2.20.*"
serde_json = "0.9"
cryogen_prelude = { version = "*", path = "../prelude" }
