[package]
name = "feature_markdown"
version = "0.1.0"
authors = ["Ferris Tseng <ferristseng@fastmail.fm>"]

[dependencies]
serde = "0.9.*"
serde_derive = "0.9.*"
serde_yaml = "0.6.*"
clap = "2.20.*"
hoedown = "6.0.*"
lib = { version = "*", path = "../lib" }
